version: '3'

networks:
  app-network:
    driver: bridge

volumes:
  mysql:
    driver: local

services:
  # Application ############################################
  app:
    build: .docker/php
    container_name: app
    entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis
    networks:
      - app-network

  # NGINX Server ############################################
  nginx:
    build:
      context: .docker/nginx
    container_name: nginx
    entrypoint: dockerize -template ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf -wait tcp://app:9000 nginx -g "daemon off;"
    environment:
      - PHP_FPM_HOST=app
      - PHP_FPM_PORT=9000
    restart: always
    tty: true
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - app-network

  # Database ###################################################
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  # Redis #################################################
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network
